services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: api
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
  database:
    image: mysql:8.0.36
    container_name: database
    ports:
      -  "3306:3306"
    volumes:
      -  ./db:/var/lib/mysql
      -  ./my_conf:/etc/mysql/conf.db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
  server:
    image: nginx:stable-alpine
    container_name: server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - database
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: app
    volumes: 
      - ./app:/src
      - /src/node_modules
    ports:
      - 8081:8081
    tty: true
    environment:
      - NODE_ENV=development
